# Генераторы

Позволяют остановить выполнение функции, а затем с помощью специального API продолжить её выполнение.

**Вызов функции генератора - возвращает объект итератор,  итерируемый объект “генератор”**

```jsx
function* generateSequence() {
  yield 1;
  yield 2;
  return 3;
}

// "функция-генератор" создаёт объект "генератор"
let generator = generateSequence();
log(generator); // [object Generator]
let one = generator.next(); // { value: 1, done: false } -- (yield 1)
let two = generator.next(); // { value: 2, done: false } -- (yield 2)
let end = generator.next(); // { value: 3, done: true } -- return 3 !!!! 
```

Основным методом генератора является `next()`. При вызове он запускает выполнение кода до ближайшей инструкции `yield <значение>` . 

По достижении `yield` выполнение функции приостанавливается, а соответствующее значение – возвращается во внешний код:

Результатом метода `next()` всегда является объект с двумя свойствами:

- `value`: значение из `yield`.
- `done`: `true`, если выполнение функции завершено, иначе `false`.
- последующие вызовы после окончания не вызовут ошибки, будут возвращать объект {done: true}

### Перебор генераторов

Генераторы являются перебираемыми объектами, возвращаемые ими значения можно перебирать через `for..of`: 

**только значения yield !!!**

```jsx
function* generateSequence() {
  yield 1;
  yield 2;
  yield 3;
  return 4; // не будет выведено в цикле !!!!!! только yield
}

let generator = generateSequence();

for(let value of generator) {
  log(value); // 1, затем 2, затем 3
}

// Также можно применить оператор расширения
let sequence = [0, ...generateSequence()]; // [0, 1, 2, 3]
```

### Композиция генераторов  *`yield*`*

Синтаксис `yield*`, позволяет «вкладывать» генераторы один в другой (осуществлять их композицию).

**yield* - можно воспринимать как один вызов  gen.next() “вложенного генератора”**

```jsx
function* generateSequence(start, end) {
  for (let i = start; i <= end; i++) yield i;
}

function* generatePasswordCodes() {
  yield* generateSequence(48, 57);

  yield* generateSequence(65, 90);
}

for(let code of generatePasswordCodes()) {
  console.log('--  code -->', code); // 48...57, 65...90
}

function* generate() {
  yield* generateSequence(48, 49);

  yield* generateSequence(65, 90);
}
const g = generate();
console.log(g.next()); // 48 -> generateSequence(48, 49)
console.log(g.next()); // 49 -> generateSequence(48, 49)

console.log(g.next()); // 65 -> generateSequence(65, 90)
console.log(g.next()); // 66 -> .....
```

### Передача значения “внутрь” генератора в процессе выполнения

1. Первый вызов `generator.next()` – всегда без аргумента, он начинает выполнение и возвращает результат первого `yield "2+2=?"`. На этой точке генератор приостанавливает выполнение.
2. При `generator.next(4)` выполнение генератора возобновляется, а `4` выходит из присваивания как результат: `let ask1 = 4`.

Обратите внимание, что внешний код не обязан немедленно вызывать `next(4)`. Ему может потребоваться время. Это не проблема, генератор подождёт.

```jsx
function* gen() {
  let ask1 = yield "2 + 2 = ?";
  console.log(ask1); // 4 пришла из внешнего кода -> generator.next(4)

  let ask2 = yield "3 * 3 = ?"
  console.log(ask2); // 9 пришла из внешнего кода -> generator.next(9)
}

let generator = gen();
console.log(generator.next()); // { value: '2 + 2 = ?', done: false }
console.log(generator.next(4)); // { value: '3 * 3 = ?', done: false }
console.log(generator.next(9)); // { value: undefined, done: true }
```

### Передача ошибки внутрь генератора

Также как и значение можно прокидывать ошибку внутрь генератора с помощью встроенного метода throw

```jsx
function* gen() {
  try {
    yield "2 + 2 = ?"; // (1)
    console.log("не дойдёт, потому что выше возникнет исключение");
  } catch(e) {
    console.log(e); // покажет ошибку -> generator.throw ....
  }
}

let generator = gen();

let question = generator.next().value; // (1) запишется значение  2 + 2 = ?

generator.throw(new Error("Ответ не найден в моей базе данных")); // (2)
```